version: '3'

services:

  logstash:
    build: .
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USE_SSL=$DATABASE_USE_SSL
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE=$DATABASE
      - SCHEDULE=$SCHEDULE
      - PIPELINE_WORKERS=1
      - XPACK_MONITORING_ENABLED=false
      - LOG_LEVEL=info
      - path.logs=/usr/share/logstash/log
      - DEBUG=$DEBUG
    # volumes:
    #   - ./pipeline:/usr/share/logstash/pipeline
    #   - ./sql:/usr/share/logstash/sql
    networks:
      - etl
    depends_on:
      - db

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_HOST: ""
    volumes:
      - ./docker/db/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - etl

networks:

  etl:
    driver: bridge
